print ("Hello World by Group 6")
print ("Member 1: Ramos - Tester")
print ("Member 2: Salcedo - Backend")
print ("Member 3: Alano - Frontend")
print ("Member 4: Chavez - Backend")
print ("Member 5: Andes - Backend")
